import {useState} from 'react';
import {Link,useNavigate,useSearchParams} from 'react-router-dom';
import {ArrowRight,BookOpen,GraduationCap,Lightbulb,Check} from 'lucide-react';
import api,{errorMessage} from '../services/api';
export default function AddSkill(){
  const navigate=useNavigate(),[params]=useSearchParams();
  const [form,setForm]=useState({title:'',type:params.get('type')==='Requesting'?'Requesting':'Offering',category:'Technology',description:'',tags:'',level:'Intermediate',availability:'Flexible'});
  const [error,setError]=useState(''),[saving,setSaving]=useState(false);
  const set=(key,value)=>setForm(current=>({...current,[key]:value}));
  const submit=async e=>{e.preventDefault();setSaving(true);setError('');try{await api.post('/skills',form);navigate('/dashboard');}catch(e){setError(errorMessage(e,'Could not save your skill.'));}finally{setSaving(false);}};
  return <main className="container page-transition"><div className="pageintro"><div><span className="eyebrow"><GraduationCap size={15}/> Make your knowledge visible</span><h1>What can you exchange?</h1><p>A clear skill profile helps the right people find you. Start with something specific.</p></div></div><div className="workspace-columns"><form onSubmit={submit} className="form card"><label className="field"><span>Skill title</span><input required minLength={2} maxLength={160} value={form.title} onChange={e=>set('title',e.target.value)} placeholder="e.g. React mentoring"/></label><div className="twocol"><Select label="I am" value={form.type} set={v=>set('type',v)} options={['Offering','Requesting']}/><Select label="Category" value={form.category} set={v=>set('category',v)} options={['Technology','Design','Languages','Communication','Business','Creative','Fitness','Cooking','Other']}/></div><div className="twocol"><Select label="Level" value={form.level} set={v=>set('level',v)} options={['Beginner','Intermediate','Advanced']}/><Select label="Availability" value={form.availability} set={v=>set('availability',v)} options={['Flexible','Weekday evenings','Weekends','Mornings']}/></div><label className="field"><span>Description</span><textarea required minLength={5} maxLength={10000} rows={5} value={form.description} onChange={e=>set('description',e.target.value)} placeholder="What could someone learn with you? Or what would you like help practicing?"/></label><label className="field"><span>Tags <small>comma separated</small></span><input maxLength={500} value={form.tags} onChange={e=>set('tags',e.target.value)} placeholder="react, javascript, frontend"/></label>{error&&<div className="error" role="alert">{error}</div>}<button className="button full" disabled={saving}>{saving?'Saving…':'Publish skill'} <ArrowRight size={16}/></button></form><aside className="workspace-aside"><div className="guide-card"><Lightbulb size={26}/><span className="section-kicker" style={{display:'block',marginTop:12}}>Make a great first connection</span><h2>Specific is a good place to start.</h2><p>“Build your first React component” gives a partner more to work with than “Coding.”</p><ul><li>Name one thing you can help someone do.</li><li>Share the experience level that feels right.</li><li>Suggest a small, achievable first session.</li></ul></div><div className="guide-card warm"><BookOpen size={24}/><h2>Your skill, at a glance</h2><span className="pill blue">{form.type==='Offering'?'Can teach':'Wants to learn'}</span><h3>{form.title||'Your next exchange starts here'}</h3><p>{form.description||'As you describe your skill, your future learning partners will see what you can explore together.'}</p><p><Check size={13}/> {form.category} · {form.level}<br/>{form.availability}</p><Link className="text-link" to="/feed">Explore how others share <ArrowRight size={14}/></Link></div></aside></div></main>;
}
function Select({label,value,set,options}) {return <label className="field"><span>{label}</span><select value={value} onChange={e=>set(e.target.value)}>{options.map(v=><option key={v}>{v}</option>)}</select></label>;}
