import {useEffect,useState} from 'react';
import {BrainCircuit,CheckCircle2,ChevronRight,Flame,Gauge,Lightbulb,ShieldCheck,Sparkles,Trophy,Users,Target,Zap} from 'lucide-react';
import api from '../services/api';

const demo={target_skill:'Python',current_skills:'JavaScript, React, SQL',goal:'Build backend APIs and become confident with FastAPI'};
export default function Innovation(){
 const [impact,setImpact]=useState({}); const [challenges,setChallenges]=useState([]); const [report,setReport]=useState([]); const [provider,setProvider]=useState(''); const [gap,setGap]=useState(null); const [quiz,setQuiz]=useState(null); const [answers,setAnswers]=useState([]); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false);
 useEffect(()=>{Promise.all([api.get('/innovation/impact'),api.get('/challenges')]).then(([a,b])=>{setImpact(a.data);setChallenges(b.data)}).catch(console.error)},[]);
 const runAI=async()=>{setLoading(true);try{const [a,b]=await Promise.all([api.post('/ai/live-match',demo),api.post('/ai/skill-gap',demo)]);setReport(a.data.matches||[]);setProvider(a.data.provider||'AI');setGap(b.data)}catch(e){console.error(e)}finally{setLoading(false)}};
 const startQuiz=async()=>{const r=await api.get('/ai/verification-quiz',{params:{skill:'Python'}});setQuiz(r.data);setAnswers(Array(r.data.questions.length).fill(null));setResult(null)};
 const submitQuiz=async()=>{const r=await api.post('/ai/verification-result',answers,{params:{skill:'Python'}});setResult(r.data)};
 return <main className="container"><section className="pageintro"><div><div className="eyebrow"><Sparkles size={15}/> Hackathon Innovation Hub</div><h1>Turn SkillSwap into a <span style={{color:'#5b4cf6'}}>knowledge economy.</span></h1><p>Show judges a product that goes beyond skill listings: AI matching, skill-gap intelligence, verification, community challenges and measurable learning impact.</p></div><button className="button" onClick={runAI}><BrainCircuit size={17}/>{loading?'Analyzing…':'Run AI Match Lab'}</button></section>
 <section className="impactgrid"><div className="impacthero card"><div className="impacticon"><Flame size={22}/></div><div><span>Community impact</span><strong>{impact.knowledge_points||0}</strong><small>knowledge points</small></div><p>{impact.impact_message||'Complete peer exchanges to measure your contribution.'}</p></div>{[['People connected',impact.people_connected||0,Users],['Learning hours',impact.learning_hours||0,Gauge],['Sessions completed',impact.sessions_completed||0,CheckCircle2],['Avg rating',impact.average_rating||0,Trophy]].map(([t,v,I])=><div className="impactstat card" key={t}><I size={18}/><span>{t}</span><strong>{v}</strong></div>)}</section>
 <section className="section"><div className="sectionhead"><div><h2>🧠 AI Match Lab</h2><p>Explainable scoring gives judges a visible AI decision pipeline.</p>{provider&&<span className="pill blue">Provider: {provider}</span>}</div></div>{report.length?<div className="innovationgrid">{report.slice(0,4).map(x=><div className="card matchreport" key={x.skill.id}><div className="matchscore">{x.score}%</div><div><h3>{x.skill.title}</h3><p>{x.skill.owner?.full_name} · {x.skill.category}</p></div><div className="bars"><label>Semantic similarity <b>{x.breakdown.semantic_similarity}</b></label><i><em style={{width:`${x.breakdown.semantic_similarity}%`}}/></i><label>Keyword fit <b>{x.breakdown.shared_keywords}</b></label><i><em style={{width:`${Math.min(100,x.breakdown.shared_keywords*5)}%`}}/></i><label>Category fit <b>{x.breakdown.category_fit}</b></label><i><em style={{width:`${x.breakdown.category_fit}%`}}/></i></div><small>{x.reason}</small></div>)}</div>:<div className="card empty innovationempty"><BrainCircuit size={32}/><h3>Run the AI Match Lab</h3><p>It compares your target skill with community skills and exposes the scoring factors instead of returning a black-box number.</p></div>}</section>
 {gap&&<section className="section"><div className="sectionhead"><div><h2>🎯 AI Skill Gap Radar</h2><p>Personalized gap analysis from your current skills and goal.</p></div></div><div className="gapgrid"><div className="card gapcard"><div className="readiness"><strong>{gap.readiness}%</strong><span>readiness</span></div><div><h3>{gap.target}</h3><p>Priority: <b>{gap.priority}</b></p><div className="tags">{gap.gap_keywords.map(x=><span key={x}>{x}</span>)}</div></div></div><div className="card gapsteps"><h3>Recommended next steps</h3>{gap.next_steps.map((x,i)=><div key={x}><span>{i+1}</span>{x}<ChevronRight size={15}/></div>)}</div></div></section>}
 <section className="section"><div className="sectionhead"><div><h2>🛡️ Skill Verification</h2><p>Give learners a lightweight proof-of-skill signal before they teach.</p></div><button className="button secondary small" onClick={startQuiz}><ShieldCheck size={15}/> Take Python challenge</button></div>{quiz?<div className="card quizbox">{quiz.questions.map((q,i)=><div className="quizq" key={q.id}><b>{i+1}. {q.question}</b><div className="options">{q.options.map((o,j)=><button className={answers[i]===j?'selected':''} onClick={()=>setAnswers(a=>a.map((v,k)=>k===i?j:v))} key={o}>{o}</button>)}</div></div>)}<button className="button" onClick={submitQuiz} disabled={answers.some(x=>x===null)}>Verify my skill</button>{result&&<div className={result.verified?'successbox':'error'}><ShieldCheck size={17}/><b>{result.score}% · {result.badge}</b><span>{result.message}</span></div>}</div>:<div className="card empty"><ShieldCheck size={30}/><h3>Verified skills build trust</h3><p>A quick challenge can unlock a visible verification signal in your hackathon demo.</p></div>}</section>
 <section className="section"><div className="sectionhead"><div><h2>🏆 Community Challenges</h2><p>Gamify learning with missions that reward teaching and building.</p></div></div><div className="grid">{challenges.map(c=><div className="card challenge"><div className="challengeicon">{c.icon}</div><span className="pill blue">{c.difficulty}</span><h3>{c.title}</h3><p>{c.description}</p><div className="skillmeta"><span>{c.metric}</span><strong><Zap size={13}/> +{c.xp} XP</strong></div></div>)}</div></section>
 <section className="section"><div className="card pitch"><div><div className="eyebrow"><Lightbulb size={14}/> Judge-ready differentiator</div><h2>From “skill marketplace” to “peer learning operating system.”</h2><p>SkillSwap closes the loop: discover a person → understand the match → verify capability → exchange skills → schedule learning → measure impact → earn reputation.</p></div><div className="pitchsteps">{[['01','Discover'],['02','Match'],['03','Verify'],['04','Exchange'],['05','Impact']].map(x=><div key={x[0]}><b>{x[0]}</b><span>{x[1]}</span></div>)}</div></div></section>
 </main>
}
