import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ArrowRight,BrainCircuit,CheckCircle2,ChevronRight,GraduationCap,ShieldCheck,Target,TrendingUp,Users} from 'lucide-react';
import api,{errorMessage} from '../services/api';
import {useAuth} from '../context/AuthContext';
import SkillCard from '../components/SkillCard';

export default function Innovation() {
  const {user}=useAuth();
  const [form,setForm]=useState({target_skill:'',current_skills:'',goal:''}),[impact,setImpact]=useState(null),[challenges,setChallenges]=useState([]),[report,setReport]=useState([]),[gap,setGap]=useState(null),[quiz,setQuiz]=useState(null),[answers,setAnswers]=useState([]),[result,setResult]=useState(null),[loading,setLoading]=useState(false),[quizBusy,setQuizBusy]=useState(false),[error,setError]=useState(''),[initialLoading,setInitialLoading]=useState(true);
  useEffect(()=>{
    Promise.allSettled([api.get('/innovation/impact'),api.get('/challenges'),api.get('/recommendations'),api.get('/skills/mine')]).then(([a,b,c,d])=>{
      if(a.status==='fulfilled')setImpact(a.value.data);
      if(b.status==='fulfilled')setChallenges(b.value.data);
      if(c.status==='fulfilled')setReport(c.value.data);
      if(d.status==='fulfilled')setForm(f=>({...f,target_skill:d.value.data.find(s=>s.type==='Requesting')?.title||'',current_skills:d.value.data.filter(s=>s.type==='Offering').map(s=>s.title).join(', ')}));
      if([a,b,c,d].some(r=>r.status==='rejected'))setError('Some of your learning activity could not load. You can still search for a match below.');
      setInitialLoading(false);
    });
  },[user.id]);
  const set=(key,value)=>setForm(f=>({...f,[key]:value}));
  const run=async e=>{e.preventDefault();setLoading(true);setError('');try{const [a,b]=await Promise.all([api.post('/ai/live-match',form),api.post('/ai/skill-gap',form)]);setReport(a.data.matches||[]);setGap(b.data);}catch(e){setError(errorMessage(e,'Could not find your matches. Please try again.'));}finally{setLoading(false);}};
  const startQuiz=async()=>{setQuizBusy(true);setError('');try{const r=await api.get('/ai/verification-quiz',{params:{skill:'Python'}});setQuiz(r.data);setAnswers(Array(r.data.questions.length).fill(null));setResult(null);}catch(e){setError(errorMessage(e,'Could not open the practice questions.'));}finally{setQuizBusy(false);}};
  const submitQuiz=async()=>{setQuizBusy(true);setError('');try{setResult((await api.post('/ai/verification-result',answers,{params:{skill:'Python'}})).data);}catch(e){setError(errorMessage(e,'Could not check your answers.'));}finally{setQuizBusy(false);}};
  return <main className="container matching-page page-transition">
    <section className="pageintro"><div><span className="eyebrow"><Target size={15}/> Your next learning connection</span><h1>A better fit. A stronger start.</h1><p>Tell us what you want to learn. Discover people, understand the fit, and make your next move.</p></div><Link className="button secondary" to="/feed?view=people">Explore the community <ArrowRight size={16}/></Link></section>
    {error&&<div className="errorbox" role="alert"><span>{error}</span></div>}
    <section className="impactgrid"><div className="impacthero card"><div className="impacticon"><TrendingUp size={24}/></div><div><span>Your shared knowledge</span><strong>{impact?.knowledge_points??'—'}</strong><small>knowledge points</small></div><p>Every skill you share and every exchange you complete helps your learning circle grow.</p></div>{[['People connected',impact?.people_connected,Users],['Learning hours',impact?.learning_hours,TrendingUp],['Completed sessions',impact?.sessions_completed,CheckCircle2],['Received rating',impact?.average_rating||'—',GraduationCap]].map(([label,value,Icon])=><div className="impactstat card" key={label}><Icon size={20}/><span>{label}</span><strong>{value??'—'}</strong></div>)}</section>
    <section className="section"><div className="workspace-columns"><form className="card form" onSubmit={run}><div className="sectionhead"><div><h2>What comes next for you?</h2><p>Start with a skill, then make the goal your own.</p></div></div><label className="field"><span>Skill I want to learn</span><input required minLength={2} maxLength={120} value={form.target_skill} onChange={e=>set('target_skill',e.target.value)} placeholder="Python, photography, public speaking…"/></label><label className="field"><span>Skills I can share</span><input value={form.current_skills} onChange={e=>set('current_skills',e.target.value)} placeholder="React, design, writing…"/></label><label className="field"><span>My learning goal</span><textarea required minLength={3} maxLength={500} rows={3} value={form.goal} onChange={e=>set('goal',e.target.value)} placeholder="I’d like to build a small project and understand the basics."/></label><button className="button full" disabled={loading||initialLoading}>{loading?'Finding your learning fit…':'Find my matches'} <ArrowRight size={16}/></button></form><aside className="guide-card"><BrainCircuit size={30}/><h2>A recommendation with a reason.</h2><p>Your skills and goals give matching a starting point. Experience levels and received reviews add context.</p><ul><li>Look for skills you can learn from each other.</li><li>Read the reason behind each recommendation.</li><li>Choose a person, then agree on a goal together.</li></ul><Link className="text-link" to="/add-skill">Update your learning profile <ArrowRight size={15}/></Link></aside></div></section>
    <section className="section"><div className="sectionhead"><div><h2>People to take your next step with</h2><p>{initialLoading?'Finding your recommendations…':'Your strongest recommendations, with the fit explained.'}</p></div></div>{report.length?<div className="grid">{report.slice(0,6).map(r=><SkillCard key={r.skill.id} skill={r.skill} match={r.score} reason={r.reason} signals={r.signals}/>)}</div>:<div className="empty card"><Users size={29}/><h3>{initialLoading?'Opening your recommendations…':'Your next match is a little context away.'}</h3><p>Add a teaching skill and a learning goal, or use the form above to explore a new direction.</p><Link className="button secondary small" to="/add-skill">Add your skills</Link></div>}</section>
    {gap&&<section className="section"><div className="sectionhead"><div><h2>Turn your goal into a next step.</h2><p>A starting point for your {gap.target} learning journey.</p></div></div><div className="gapgrid"><div className="guide-card"><Target size={25}/><h2>Concepts to explore</h2><div className="tags">{gap.gap_keywords.map(g=><span key={g}>{g}</span>)}</div><p>Use these as conversation starters. Agree with your partner on what to practice first.</p></div><div className="card gapsteps"><h3>A little structure helps</h3>{gap.next_steps.map((step,i)=><div key={step}><span>{i+1}</span>{step}<ChevronRight size={15}/></div>)}</div></div></section>}
    <section className="section"><div className="sectionhead"><div><h2>Check your Python foundations</h2><p>A quick practice challenge to see what feels familiar.</p></div><button className="button secondary small" onClick={startQuiz} disabled={quizBusy}>{quizBusy?'Opening…':'Try the challenge'}</button></div>{quiz?<div className="card quizbox">{quiz.questions.map((q,i)=><fieldset className="quizq" key={q.id}><legend>{i+1}. {q.question}</legend><div className="options">{q.options.map((o,j)=><button type="button" aria-pressed={answers[i]===j} className={answers[i]===j?'selected':''} key={o} onClick={()=>setAnswers(a=>a.map((v,k)=>k===i?j:v))}>{o}</button>)}</div></fieldset>)}<button className="button" onClick={submitQuiz} disabled={quizBusy||answers.some(a=>a===null)}>{quizBusy?'Checking…':'Check my answers'}</button>{result&&<div className="successbox" role="status"><ShieldCheck size={18}/><span>{result.score}% correct. {result.verified?'A strong start — put it into practice with a peer.':'Keep practicing and try again when you’re ready.'}</span></div>}</div>:<div className="explore-tip"><ShieldCheck size={30}/><div><h2>Know where you’re starting.</h2><p>A few focused questions can reveal what to practice before your next exchange.</p></div></div>}</section>
    <section className="section"><div className="sectionhead"><div><h2>A little inspiration for your next exchange</h2><p>Choose a community challenge and give your learning a direction.</p></div></div><div className="grid">{challenges.map(c=><article className="card challenge" key={c.id}><div className="challengeicon">{c.icon}</div><h3>{c.title}</h3><p>{c.description}</p><div className="skillmeta"><span>{c.metric}</span></div><Link className="cardaction" to="/feed">Find a learning partner <ArrowRight size={14}/></Link></article>)}</div></section>
  </main>;
}
