import {useEffect,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {ArrowLeft,ArrowUpRight,MapPin,Star,ArrowRightLeft} from 'lucide-react';
import api,{errorMessage} from '../services/api';
import {Avatar} from '../components/MemberCard';

export default function MemberProfile() {
  const {id}=useParams(),[member,setMember]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  useEffect(()=>{const controller=new AbortController();setMember(null);setError('');api.get('/community/members/'+id,{signal:controller.signal}).then(r=>setMember(r.data)).catch(e=>{if(!controller.signal.aborted)setError(errorMessage(e,'Could not load this member.'));});return()=>controller.abort();},[id,retry]);
  if(error)return <main className="container"><div className="errorbox" role="alert"><span>{error}</span><button className="button small" onClick={()=>setRetry(n=>n+1)}>Try again</button></div><Link to="/feed?view=people" className="text-link">Back to community</Link></main>;
  if(!member)return <main className="container loading" role="status">Getting to know your next learning partner…</main>;
  return <main className="container profile-page page-transition"><Link className="back" to="/feed?view=people"><ArrowLeft size={15}/> Back to community</Link><div className="profilehead"><Avatar person={member}/><div><span className="section-kicker">Your learning community</span><h1>{member.full_name}</h1><p><MapPin size={12}/> {member.location||'Open to remote learning'}</p></div></div><div className="workspace-columns"><div><section className="guide-card" style={{marginBottom:22}}><h2>A little about {member.full_name.split(' ')[0]}</h2><p>{member.bio||'A curious member of the SkillSwap community. Explore their skills to find a shared starting point.'}</p></section>{[['Offering','What I can teach'],['Requesting','What I want to learn']].map(([type,title])=><section className="section" key={type}><div className="sectionhead"><h2>{title}</h2></div><div className="grid two">{member.skills.filter(s=>s.type===type).map(s=><article className="card skillcard" key={s.id} data-category={s.category}><div className="cardtop"><span className={type==='Offering'?'pill green':'pill blue'}>{type==='Offering'?'Can teach':'Wants to learn'}</span><span>{s.category}</span></div><h3>{s.title}</h3><p>{s.description}</p><div className="skillmeta"><span>{s.level}</span><span>{s.availability}</span></div><Link className="cardaction" to={'/skill/'+s.id}>Explore an exchange <ArrowUpRight size={15}/></Link></article>)}</div>{!member.skills.some(s=>s.type===type)&&<p className="aside-note">This member is still adding their skills.</p>}</section>)}</div><aside className="workspace-aside"><section className="guide-card warm"><ArrowRightLeft size={27}/><h2>Find your shared starting point.</h2><p>Choose a skill that interests you. Offer something you know, and send a friendly introduction with your swap proposal.</p><p>After proposing a swap, you can chat. Once accepted, you can schedule and meet in your private learning room.</p></section><section className="guide-card"><Star size={24}/><h2>Community feedback</h2><strong>{member.review_count?member.rating+' / 5 · '+member.review_count+' reviews':'A new learning connection'}</strong>{member.reviews.map(r=><article className="received-review" key={r.id}><strong>{r.author}</strong> <span>{r.score}/5</span><p>{r.review||'Shared a rating after an exchange.'}</p></article>)}{!member.review_count&&<p>Every reputation starts with a first exchange. Received reviews will appear here.</p>}</section></aside></div></main>;
}
